/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Comunicacion.*;
import Controlador.*;
import Modelo.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Seba
 */
public class Contactos extends javax.swing.JFrame {
    
    /**
     * Creates new form Contactos
     */
    DefaultListModel listModel;
    
    public Contactos() {
        initComponents();
        this.setTitle(Chat.getCliente().getNombre()+" - Contactos");
        setResizable(false);
        setLocationRelativeTo(null);
        refrescarContactos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        btnNuevoChat = new javax.swing.JButton();
        txtNuevoChat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList2.setModel(new DefaultListModel());
        jList2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNuevoChat.setText("Nuevo chat");
        btnNuevoChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoChatActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(btnNuevoChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNuevoChat))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(txtNuevoChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refrescarContactos();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        int indexConversa = jList2.getSelectedIndex();
        new VistaChat(indexConversa).setVisible(true);
    }//GEN-LAST:event_jList2MouseClicked

    private void btnNuevoChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoChatActionPerformed
        String receptor = txtNuevoChat.getText();
        int idContacto = Comunicador.obtenerIdContacto(receptor);
        
        if(idContacto==0 && idContacto==Chat.getClienteId()){
            // usuario no existe
            JOptionPane.showMessageDialog(this, "Usuario no valido");
        }
        else if(idContacto==-1){
            //error de conexion
            JOptionPane.showMessageDialog(this, "Error de conexion");
        }
        else{
            // idcontacto fue obtenido
            // bug: conversaciones duplicadas
            int idConversa = Comunicador.crearConversa(Chat.getClienteId(), idContacto);
            if(idConversa!=-1){
                Usuario nContacto = new Usuario(idContacto, receptor);
                Conversacion nConversa = new Conversacion(idConversa, nContacto);
                JOptionPane.showMessageDialog(this, "Conversacion creada");
                Chat.addContacto(nContacto);
                Chat.addConversacion(nConversa);
                int indexConversa = Chat.getAlConversacion().indexOf(nConversa);
                new VistaChat(indexConversa).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Error de conexion");
            }            
        }
        refrescarContactos();
    }//GEN-LAST:event_btnNuevoChatActionPerformed

    private void refrescarContactos(){
        String nombre;
        listModel = new DefaultListModel();
        Comunicador.conversacionesObtener(Chat.getClienteId());
        
        for(Conversacion u : Chat.getAlConversacion()){
            nombre = u.getContacto().getNombre();
            listModel.addElement(nombre);
        }
        jList2.setModel(listModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoChat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNuevoChat;
    // End of variables declaration//GEN-END:variables


}
